# Generated by Django 4.2.1 on 2023-05-25 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoElement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='AudioFragment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('audio_type', models.CharField(choices=[('vo', 'voice over'), ('bg_music', 'background music')], max_length=20)),
                ('volume', models.IntegerField()),
                ('url', models.CharField(max_length=200, null=True)),
                ('duration', models.JSONField(default=dict)),
                ('video_element', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.videoelement')),
            ],
        ),
    ]
