# Generated by Django 4.2.1 on 2023-05-25 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiofragment',
            name='audio_type',
            field=models.CharField(choices=[('vo', 'voice over'), ('bg_music', 'background music'), ('video_music', 'video music')], max_length=30),
        ),
    ]
