# Generated by Django 4.2.1 on 2023-05-25 18:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_audiofragment_audio_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiofragment',
            name='duration',
        ),
        migrations.AddField(
            model_name='audiofragment',
            name='end_time',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='audiofragment',
            name='start_time',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='audiofragment',
            name='volume',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
