# Generated by Django 4.2.1 on 2023-05-25 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_audiofragment_duration_audiofragment_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoelement',
            name='url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
