# Generated by Django 4.2.1 on 2023-05-28 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_videoelement_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioElement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='audiofragment',
            name='audio_element',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.audioelement'),
        ),
    ]
